# Generated by Django 5.2.7 on 2025-11-06 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amadeus_id', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('one_way', models.BooleanField(default=False)),
                ('number_of_bookable_seats', models.IntegerField()),
                ('last_ticketing_date', models.DateField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=50)),
                ('flight_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='flights.flightoffer')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_airport', models.CharField(max_length=10)),
                ('departure_terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('departure_time', models.DateTimeField()),
                ('arrival_airport', models.CharField(max_length=10)),
                ('arrival_terminal', models.CharField(blank=True, max_length=10, null=True)),
                ('arrival_time', models.DateTimeField()),
                ('carrier_code', models.CharField(max_length=10)),
                ('flight_number', models.CharField(max_length=10)),
                ('aircraft_code', models.CharField(max_length=10)),
                ('duration', models.CharField(max_length=50)),
                ('number_of_stops', models.IntegerField()),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='flights.itinerary')),
            ],
        ),
    ]
