# Generated by Django 5.2.7 on 2025-11-10 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flightbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightbooking',
            name='reference_code',
            field=models.CharField(default='A1', editable=False, max_length=20, unique=True),
        ),
    ]
