# Generated by Django 5.2.7 on 2025-11-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_flightbooking_reference_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbooking',
            name='reference_code',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
